Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0aa7d40eeae50c9a9
      InstanceType: t2.micro
      Tags:
        - Key: "Name"
          Value: !Join ["-", [Lets, see, ChangeSet]]