Resources:
  MyInstance:
    Type: AWS::EC2::Instance    
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0aa7d40eeae50c9a9
      Tags:
        - Key: "Name"
          Value: !Join
            - " "
            - - "My Instance in"
              - !Ref AWS::Region #Pseudo Parameter
      